spring:
    datasource:
        driverClassName: org.postgresql.Driver
        platform: postgres
        url: jdbc:postgresql://ec2-54-221-214-3.compute-1.amazonaws.com:5432/d7qgb8miallhmv
        username: upxhevjsronfqy
        password: 4e8070664eaa4d3b1e153e277205145465c9fc080eecada726e7e392f64089f5
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        ##show-sql: true

server:
    port: 8090
    servlet:
        context-path: /api

logging:
    level:
        # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
        org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN


        